export const tableData = [
    {
        typ: 'Auftrag',
        mandant: 'Attensam',
        kNummer: new Date().getTime().toString().split('').slice(0, 8).join(''),
        kName: 'ACME',
        nummer: `ATT${(Math.random() * 100000).toFixed()}`,
        strasse: 'Wittmayergasse',
        hausnummer: (Math.random() * 80).toFixed(),
        plz: 1120,
        ort: 'Wien',
    },
    {
        typ: 'Zähler',
        mandant: 'Attensam',
        kNummer: new Date().getTime().toString().split('').slice(0, 8).join(''),
        kName: 'ACME',
        nummer: `W${(Math.random() * 10000).toFixed()}`,
        strasse: 'Wittmayergasse',
        hausnummer: (Math.random() * 80).toFixed(),
        plz: 1150,
        ort: 'Wien',
    },
    {
        typ: 'Auftrag',
        mandant: 'Attensam',
        kNummer: new Date().getTime().toString().split('').slice(0, 8).join(''),
        kName: 'ACME',
        nummer: `ATT${(Math.random() * 100000).toFixed()}`,
        strasse: 'Wittmayergasse',
        hausnummer: (Math.random() * 80).toFixed(),
        plz: 1220,
        ort: 'Wien',
    },
    {
        typ: 'Zähler',
        mandant: 'Attensam',
        kNummer: new Date().getTime().toString().split('').slice(0, 8).join(''),
        kName: 'ACME',
        nummer: `W${(Math.random() * 10000).toFixed()}`,
        strasse: 'Wittmayergasse',
        hausnummer: (Math.random() * 80).toFixed(),
        plz: 1190,
        ort: 'Wien',
    },
    {
        typ: 'Auftrag',
        mandant: 'Attensam',
        kNummer: new Date().getTime().toString().split('').slice(0, 8).join(''),
        kName: 'ACME',
        nummer: `ATT${(Math.random() * 100000).toFixed()}`,
        strasse: 'Wittmayergasse',
        hausnummer: (Math.random() * 80).toFixed(),
        plz: 1200,
        ort: 'Wien',
    },
    {
        typ: 'Zähler',
        mandant: 'Attensam',
        kNummer: new Date().getTime().toString().split('').slice(0, 8).join(''),
        kName: 'ACME',
        nummer: `W${(Math.random() * 10000).toFixed()}`,
        strasse: 'Wittmayergasse',
        hausnummer: (Math.random() * 80).toFixed(),
        plz: 1020,
        ort: 'Wien',
    },
    {
        typ: 'Auftrag',
        mandant: 'Attensam',
        kNummer: new Date().getTime().toString().split('').slice(0, 8).join(''),
        kName: 'ACME',
        nummer: `ATT${(Math.random() * 100000).toFixed()}`,
        strasse: 'Wittmayergasse',
        hausnummer: (Math.random() * 80).toFixed(),
        plz: 1130,
        ort: 'Wien',
    },
    {
        typ: 'Auftrag',
        mandant: 'Attensam',
        kNummer: new Date().getTime().toString().split('').slice(0, 8).join(''),
        kName: 'ACME',
        nummer: `ATT${(Math.random() * 100000).toFixed()}`,
        strasse: 'Wittmayergasse',
        hausnummer: (Math.random() * 80).toFixed(),
        plz: 1230,
        ort: 'Wien',
    },
    {
        typ: 'Zähler',
        mandant: 'Attensam',
        kNummer: new Date().getTime().toString().split('').slice(0, 8).join(''),
        kName: 'ACME',
        nummer: `W${(Math.random() * 10000).toFixed()}`,
        strasse: 'Wittmayergasse',
        hausnummer: (Math.random() * 80).toFixed(),
        plz: 1110,
        ort: 'Wien',
    },
    {
        typ: 'Auftrag',
        mandant: 'Attensam',
        kNummer: new Date().getTime().toString().split('').slice(0, 8).join(''),
        kName: 'ACME',
        nummer: `ATT${(Math.random() * 100000).toFixed()}`,
        strasse: 'Wittmayergasse',
        hausnummer: (Math.random() * 80).toFixed(),
        plz: 1050,
        ort: 'Wien',
    },
    {
        typ: 'Auftrag',
        mandant: 'Attensam',
        kNummer: new Date().getTime().toString().split('').slice(0, 8).join(''),
        kName: 'ACME',
        nummer: `ATT${(Math.random() * 100000).toFixed()}`,
        strasse: 'Wittmayergasse',
        hausnummer: (Math.random() * 80).toFixed(),
        plz: 1080,
        ort: 'Wien',
    },
];
