export const tableData = [
    {
        typ: 'Auftrag',
        mandant: 'Firma A',
        kNummer: 100000,
        kName: 'ACME',
        nummer: `ATT${(Math.random() * 100000).toFixed()}`,
        strasse: 'Wittmayergasse',
        hausnummer: 26,
        plz: 1120,
        ort: 'Wien',
    },
    {
        typ: 'Zähler',
        mandant: 'Firma A',
        kNummer: 100000,
        kName: 'ACME',
        nummer: `W${(Math.random() * 10000).toFixed()}`,
        strasse: 'Wittmayergasse',
        hausnummer: 26,
        plz: 1120,
        ort: 'Wien',
    },
    {
        typ: 'Auftrag',
        mandant: 'Firma B',
        kNummer: 100001,
        kName: 'ACME',
        nummer: `ATT${(Math.random() * 100000).toFixed()}`,
        strasse: 'Kaiserstraße',
        hausnummer: 42,
        plz: 1070,
        ort: 'Wien',
    },
    {
        typ: 'Zähler',
        mandant: 'Firma B',
        kNummer: 100001,
        kName: 'ACME',
        nummer: `W${(Math.random() * 10000).toFixed()}`,
        strasse: 'Kaiserstraße',
        hausnummer: 42,
        plz: 1070,
        ort: 'Wien',
    },
    {
        typ: 'Auftrag',
        mandant: 'Firma C',
        kNummer: 100002,
        kName: 'ACME',
        nummer: `ATT${(Math.random() * 100000).toFixed()}`,
        strasse: 'Hütteldorfer Straße',
        hausnummer: 142,
        plz: 1140,
        ort: 'Wien',
    },
    {
        typ: 'Zähler',
        mandant: 'Firma C',
        kNummer: 100002,
        kName: 'ACME',
        nummer: `W${(Math.random() * 10000).toFixed()}`,
        strasse: 'Hütteldorfer Straße',
        hausnummer: 142,
        plz: 1140,
        ort: 'Wien',
    },
];
